version: "3.9"

services:
  app:
    build: .
    container_name: app_python
    depends_on:
      - db
    volumes:
      - .:/app
    command: python app.py

  db:
    image: postgres:15
    container_name: app_postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave123
      POSTGRES_DB: basededatos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
